trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node'

- script: npm install
  displayName: 'Install dependencies'

- script: echo "Build complete"
  displayName: 'Build step'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'azure-conn'
    appName: 'gpt-app-test'
    package: '.'
    displayName: 'Deploy to Azure'